<?php

namespace ContainerGN8jdcC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QWo18u9Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qWo18u9' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qWo18u9'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'resto' => ['privates', '.errored..service_locator.qWo18u9.App\\Entity\\Resto', NULL, 'Cannot autowire service ".service_locator.qWo18u9": it references class "App\\Entity\\Resto" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'resto' => 'App\\Entity\\Resto',
        ]);
    }
}
