<?php

namespace ContainerGN8jdcC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getResto2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.tg6Kc3x.App\Entity\Resto' shared service.
     *
     * @return \App\Entity\Resto
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.tg6Kc3x": it references class "App\\Entity\\Resto" but no such service exists.');
    }
}
