<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLmZaWlw\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLmZaWlw/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLmZaWlw.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLmZaWlw\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLmZaWlw\App_KernelDevDebugContainer([
    'container.build_hash' => 'LmZaWlw',
    'container.build_id' => '952e57da',
    'container.build_time' => 1714264273,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLmZaWlw');
